osx_image: xcode10.2
language: objective-c
cache:
  - bundler
  - cocoapods

before_install:
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update
  - cp ./mock-GoogleService-Info.plist GoogleService-Info.plist
  - sed -i '' 's/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/' Info.plist
  - gem install xcodeproj
  - ruby ./info_script.rb

script: ./test.sh

branches:
  only:
    - master
